baseURL = "https://trofimtsovaee.github.io/portfolio-hugo-herzen"
languageCode = 'en-us'
title = 'My New Hugo Site'

theme = "loficode"

[params]
  description = "Your site description"

  [params.author]
    name = "Your Name"
    image = "images/profile.png"

  # Profile section
  [params.profile]
    name = "Your Name"
    tagline = "Your tagline here"
    photo = "/images/profile.png"

  # Social links - Supported platforms: github, twitter, linkedin, email, mastodon, youtube, instagram, facebook
  [params.social]
    github = "meimakes"
    twitter = "meimakes"
    # linkedin = "your-linkedin-username"
    # email = "your-email@example.com"
    # mastodon = "https://mastodon.social/@yourusername"
    # youtube = "https://youtube.com/@yourusername"
    # instagram = "your-instagram-username"
    # facebook = "your-facebook-username"

# Navigation menu
[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 10

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 20